package gui;

import jail.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Hussain
 */
public class ViewPrisonerDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewPrisonerDetails
     */
    Prisoner p;
    private DefaultListModel mod;

    public ViewPrisonerDetails() {
        initComponents();
        menu.add(panel);
        mod = new DefaultListModel();
        list.setModel(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        menu = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        searchtf = new javax.swing.JTextField();
        or = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        upperLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf10 = new javax.swing.JTextField();
        tf9 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tf7 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        tf8 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MainLabel1 = new javax.swing.JLabel();

        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );

        menu.setFocusable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(880, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 30)); // NOI18N
        jLabel4.setText("   View Prisoner Details");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setText("Search with:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 81, -1, 40));

        cb1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one....", "Name", "ID", "Inmate ID" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        jPanel1.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 150, 40));

        searchtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtfActionPerformed(evt);
            }
        });
        searchtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtfKeyReleased(evt);
            }
        });
        jPanel1.add(searchtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 190, 40));

        or.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jPanel1.add(or, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 140, 40));

        jButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 100, 40));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 840, 80));

        upperLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        upperLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(upperLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 30));

        tf1.setEditable(false);
        jPanel1.add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 240, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("age");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, 30));

        tf2.setEditable(false);
        jPanel1.add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 290, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Gender");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 30));

        tf3.setEditable(false);
        jPanel1.add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 240, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Date Of Entry");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 30));

        tf10.setEditable(false);
        jPanel1.add(tf10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 290, 30));

        tf9.setEditable(false);
        jPanel1.add(tf9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 240, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Duration");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Inmate ID");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("ID");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, 30));

        tf7.setEditable(false);
        tf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf7ActionPerformed(evt);
            }
        });
        jPanel1.add(tf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 240, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Remaining Time");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, 30));

        tf4.setEditable(false);
        jPanel1.add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 290, 30));

        tf8.setEditable(false);
        jPanel1.add(tf8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 290, 30));

        tf6.setEditable(false);
        jPanel1.add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 290, 30));

        tf5.setEditable(false);
        jPanel1.add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 240, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Offense");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Cell Number");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 30));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 840, 380));

        MainLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(MainLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, 860, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 872, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        if(cb1.getSelectedIndex() != 0){
            or.setText("Enter " + cb1.getSelectedItem() + ":");
            tf1.setText("");
            tf2.setText("");
            tf3.setText("");
            tf4.setText("");
            tf5.setText("");
            tf6.setText("");
            tf7.setText("");
            tf8.setText("");
            tf9.setText("");
            tf10.setText("");
            searchtf.setText("");
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void searchtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (cb1.getSelectedIndex() == 3) {
            p = Database.getPrisonerByInmateID(searchtf.getText());
        } else if (cb1.getSelectedIndex() == 2) {
            p = Database.getPrisonerByID(searchtf.getText());
        } else if (cb1.getSelectedIndex() == 1){
            String[] s = searchtf.getText().split(" ");
            if (s.length != 2) {
                JOptionPane.showMessageDialog(rootPane, "Please select name from the list");
            } else {
                p = Database.getPrisonerByID(s[1]);
            }
        }else {
            JOptionPane.showMessageDialog(rootPane, "Please select search method");
        }
        if (p == null && cb1.getSelectedIndex() != 0) {
            JOptionPane.showMessageDialog(rootPane, "Please enter a valid ID");
        } else if (cb1.getSelectedIndex() != 0) {
            searchtf.setText("");
            tf1.setText(p.getName());
            tf2.setText(p.getDOB().getAge() + "");
            if (p.getGender() == 'M') {
                tf3.setText("Male");
            } else {
                tf3.setText("Female");
            }
            tf4.setText(p.getID());
            tf5.setText(p.getOffense());
            tf6.setText(p.getInmateID());
            tf7.setText(p.getEntry().toString());
            tf8.setText(p.getDuration() + "");
            tf9.setText(p.getCellNumber() + "");
            tf10.setText(p.getEntry().releaseDate(p.getDuration()).remainingTime() + "w");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf7ActionPerformed

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        searchtf.setText(list.getSelectedValue());
        menu.setVisible(false);
    }//GEN-LAST:event_listMouseClicked

    private void searchtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtfKeyReleased
        if (cb1.getSelectedIndex() == 1) {
            String search = searchtf.getText().trim().toLowerCase();
            if (!search.equals("")) {
                mod.removeAllElements();
                for (Prisoner p : Database.getPrisoners()) {
                    if (p.getName().toLowerCase().startsWith(search)) {
                        mod.addElement(p.getName() + " " + p.getID());
                    }
                }
                menu.show(searchtf, 0, searchtf.getHeight());
            }
        }
    }//GEN-LAST:event_searchtfKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainLabel1;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JLabel or;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField searchtf;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf10;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    private javax.swing.JLabel upperLabel;
    // End of variables declaration//GEN-END:variables
}
