/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import jail.Database;
import jail.Visitor;

/**
 *
 * @author husse
 */
public class Visitation extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddPrisner
     */
    public Visitation() {
        initComponents();
        initSettings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        actionType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        addVisitation = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        visitationId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        visitYear = new javax.swing.JComboBox<>();
        visitDay = new javax.swing.JComboBox<>();
        visitMonth = new javax.swing.JComboBox<>();
        visitHour = new javax.swing.JComboBox<>();
        visitTime = new javax.swing.JComboBox<>();
        existingVisitor = new javax.swing.JRadioButton();
        newVisitor = new javax.swing.JRadioButton();
        existingVisitorPanel1 = new javax.swing.JPanel();
        eVisitorName1 = new javax.swing.JTextField();
        eVisitorDay1 = new javax.swing.JComboBox<>();
        eVisitorMonth1 = new javax.swing.JComboBox<>();
        eVisitorGender1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        eVisitorIdNumber1 = new javax.swing.JTextField();
        eVisitorYear1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        eVisitorID1 = new javax.swing.JTextField();
        prisonerStatus = new javax.swing.JLabel();
        existingVisitorPanel = new javax.swing.JPanel();
        eVisitorName = new javax.swing.JTextField();
        eVisitorDay = new javax.swing.JComboBox<>();
        eVisitorMonth = new javax.swing.JComboBox<>();
        eVisitorGender = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        eVisitorIdNumber = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        eVisitorID = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        visitorStatus = new javax.swing.JLabel();
        eVisitorYear = new javax.swing.JTextField();
        newVisitorPanel = new javax.swing.JPanel();
        nVisitorName = new javax.swing.JTextField();
        nVisitorDay = new javax.swing.JComboBox<>();
        nVisitorMonth = new javax.swing.JComboBox<>();
        nVisitorGender = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nVisitorIdNumber = new javax.swing.JTextField();
        nVisitorYear = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(880, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Select your action:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        actionType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        actionType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Add Visitation", "Edit Visitation", "View Visitation" }));
        actionType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionTypeActionPerformed(evt);
            }
        });
        jPanel1.add(actionType, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("   Visitation");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 56));

        addVisitation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Visitation ID:");
        addVisitation.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        visitationId.setText("0000");
        addVisitation.add(visitationId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 160, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Date of Visit:");
        addVisitation.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Time of Visit:");
        addVisitation.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        visitYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        visitYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitYearActionPerformed(evt);
            }
        });
        addVisitation.add(visitYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 60, -1));

        visitDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        visitDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitDayActionPerformed(evt);
            }
        });
        addVisitation.add(visitDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 40, -1));

        visitMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        visitMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitMonthActionPerformed(evt);
            }
        });
        addVisitation.add(visitMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 40, -1));

        visitHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        visitHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitHourActionPerformed(evt);
            }
        });
        addVisitation.add(visitHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 40, -1));

        visitTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        visitTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitTimeActionPerformed(evt);
            }
        });
        addVisitation.add(visitTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 60, -1));

        existingVisitor.setText("Existing Visitor");
        existingVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingVisitorActionPerformed(evt);
            }
        });
        addVisitation.add(existingVisitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        newVisitor.setText("New Visitor");
        newVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newVisitorActionPerformed(evt);
            }
        });
        addVisitation.add(newVisitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        existingVisitorPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eVisitorName1.setEnabled(false);
        eVisitorName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eVisitorName1ActionPerformed(evt);
            }
        });
        existingVisitorPanel1.add(eVisitorName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 160, -1));

        eVisitorDay1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        eVisitorDay1.setEnabled(false);
        eVisitorDay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eVisitorDay1ActionPerformed(evt);
            }
        });
        existingVisitorPanel1.add(eVisitorDay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 40, -1));

        eVisitorMonth1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        eVisitorMonth1.setEnabled(false);
        eVisitorMonth1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eVisitorMonth1ActionPerformed(evt);
            }
        });
        existingVisitorPanel1.add(eVisitorMonth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 40, -1));

        eVisitorGender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        eVisitorGender1.setEnabled(false);
        eVisitorGender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eVisitorGender1ActionPerformed(evt);
            }
        });
        existingVisitorPanel1.add(eVisitorGender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 80, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("ID Number:");
        jLabel16.setEnabled(false);
        existingVisitorPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Prisoner Gender:");
        jLabel17.setEnabled(false);
        existingVisitorPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Date of Birth:");
        jLabel18.setEnabled(false);
        existingVisitorPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Prisoner Name:");
        jLabel19.setEnabled(false);
        existingVisitorPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        eVisitorIdNumber1.setEnabled(false);
        eVisitorIdNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eVisitorIdNumber1ActionPerformed(evt);
            }
        });
        existingVisitorPanel1.add(eVisitorIdNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 160, -1));

        eVisitorYear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004" }));
        eVisitorYear1.setEnabled(false);
        eVisitorYear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eVisitorYear1ActionPerformed(evt);
            }
        });
        existingVisitorPanel1.add(eVisitorYear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 60, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Prisoner ID:");
        existingVisitorPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        eVisitorID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eVisitorID1ActionPerformed(evt);
            }
        });
        existingVisitorPanel1.add(eVisitorID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 160, -1));

        prisonerStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prisonerStatus.setForeground(new java.awt.Color(255, 0, 0));
        existingVisitorPanel1.add(prisonerStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 250, 20));

        addVisitation.add(existingVisitorPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 290, 190));

        existingVisitorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eVisitorName.setEnabled(false);
        eVisitorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eVisitorNameActionPerformed(evt);
            }
        });
        existingVisitorPanel.add(eVisitorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 160, -1));

        eVisitorDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        eVisitorDay.setEnabled(false);
        eVisitorDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eVisitorDayActionPerformed(evt);
            }
        });
        existingVisitorPanel.add(eVisitorDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 40, -1));

        eVisitorMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        eVisitorMonth.setEnabled(false);
        eVisitorMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eVisitorMonthActionPerformed(evt);
            }
        });
        existingVisitorPanel.add(eVisitorMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 40, -1));

        eVisitorGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        eVisitorGender.setEnabled(false);
        eVisitorGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eVisitorGenderActionPerformed(evt);
            }
        });
        existingVisitorPanel.add(eVisitorGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 80, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Visitor Gender:");
        jLabel12.setEnabled(false);
        existingVisitorPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Date of Birth:");
        jLabel13.setEnabled(false);
        existingVisitorPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Visitor Name:");
        jLabel14.setEnabled(false);
        existingVisitorPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        eVisitorIdNumber.setEnabled(false);
        eVisitorIdNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eVisitorIdNumberActionPerformed(evt);
            }
        });
        existingVisitorPanel.add(eVisitorIdNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 160, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Visitor ID:");
        existingVisitorPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        eVisitorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eVisitorIDActionPerformed(evt);
            }
        });
        existingVisitorPanel.add(eVisitorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 160, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("ID Number:");
        jLabel21.setEnabled(false);
        existingVisitorPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        visitorStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        visitorStatus.setForeground(new java.awt.Color(255, 0, 0));
        existingVisitorPanel.add(visitorStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 250, 20));

        eVisitorYear.setEnabled(false);
        existingVisitorPanel.add(eVisitorYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 60, -1));

        addVisitation.add(existingVisitorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 290, 180));

        newVisitorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nVisitorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nVisitorNameActionPerformed(evt);
            }
        });
        newVisitorPanel.add(nVisitorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 160, -1));

        nVisitorDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        nVisitorDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nVisitorDayActionPerformed(evt);
            }
        });
        newVisitorPanel.add(nVisitorDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 40, -1));

        nVisitorMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        nVisitorMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nVisitorMonthActionPerformed(evt);
            }
        });
        newVisitorPanel.add(nVisitorMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 40, -1));

        nVisitorGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        nVisitorGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nVisitorGenderActionPerformed(evt);
            }
        });
        newVisitorPanel.add(nVisitorGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 80, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("ID Number:");
        newVisitorPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Visitor Gender:");
        newVisitorPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Date of Birth:");
        newVisitorPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Visitor Name:");
        newVisitorPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        nVisitorIdNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nVisitorIdNumberActionPerformed(evt);
            }
        });
        newVisitorPanel.add(nVisitorIdNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 160, -1));

        nVisitorYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004" }));
        nVisitorYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nVisitorYearActionPerformed(evt);
            }
        });
        newVisitorPanel.add(nVisitorYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 60, -1));

        addVisitation.add(newVisitorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 290, 150));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Create");
        jButton1.setEnabled(false);
        addVisitation.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 130, -1));

        jPanel1.add(addVisitation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 820, 410));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 860, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visitYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitYearActionPerformed

    private void visitDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitDayActionPerformed

    private void visitMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitMonthActionPerformed

    private void visitHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitHourActionPerformed

    private void visitTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitTimeActionPerformed

    private void nVisitorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nVisitorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nVisitorNameActionPerformed

    private void nVisitorDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nVisitorDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nVisitorDayActionPerformed

    private void nVisitorGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nVisitorGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nVisitorGenderActionPerformed

    private void nVisitorYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nVisitorYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nVisitorYearActionPerformed

    private void nVisitorMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nVisitorMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nVisitorMonthActionPerformed

    private void nVisitorIdNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nVisitorIdNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nVisitorIdNumberActionPerformed

    private void newVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newVisitorActionPerformed
        newVisitorPanel.setVisible(true);
        existingVisitorPanel.setVisible(false);
    }//GEN-LAST:event_newVisitorActionPerformed

    private void eVisitorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eVisitorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eVisitorNameActionPerformed

    private void eVisitorDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eVisitorDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eVisitorDayActionPerformed

    private void eVisitorMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eVisitorMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eVisitorMonthActionPerformed

    private void eVisitorGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eVisitorGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eVisitorGenderActionPerformed

    private void eVisitorIdNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eVisitorIdNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eVisitorIdNumberActionPerformed

    private void eVisitorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eVisitorIDActionPerformed
        Visitor visitor = Database.getVisitor(eVisitorID.getText());
        if (!(visitor == null)) {
            eVisitorName.setText(visitor.getName());
            eVisitorDay.setSelectedIndex(visitor.getDOB().getDay());
            eVisitorMonth.setSelectedIndex(visitor.getDOB().getMonth());
            eVisitorYear.setText(visitor.getDOB().getYear() + "");
            eVisitorGender.setSelectedIndex((visitor.getGender() == 'M')? 0 : 1);
            eVisitorIdNumber.setText(visitor.getID());
        } else {
            eVisitorName.setText("");
            eVisitorDay.setSelectedIndex(0);
            eVisitorMonth.setSelectedIndex(0);
            eVisitorYear.setText("");
            eVisitorGender.setSelectedIndex(0);
            eVisitorIdNumber.setText("");
        }
    }//GEN-LAST:event_eVisitorIDActionPerformed

    private void existingVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingVisitorActionPerformed
        newVisitorPanel.setVisible(false);
        existingVisitorPanel.setVisible(true);
    }//GEN-LAST:event_existingVisitorActionPerformed

    private void eVisitorName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eVisitorName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eVisitorName1ActionPerformed

    private void eVisitorDay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eVisitorDay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eVisitorDay1ActionPerformed

    private void eVisitorMonth1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eVisitorMonth1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eVisitorMonth1ActionPerformed

    private void eVisitorGender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eVisitorGender1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eVisitorGender1ActionPerformed

    private void eVisitorIdNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eVisitorIdNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eVisitorIdNumber1ActionPerformed

    private void eVisitorYear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eVisitorYear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eVisitorYear1ActionPerformed

    private void eVisitorID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eVisitorID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eVisitorID1ActionPerformed

    private void actionTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionTypeActionPerformed
        if (actionType.getSelectedIndex() == 1) {
            addVisitation.setVisible(true);
        }
    }//GEN-LAST:event_actionTypeActionPerformed

    private void initSettings() {
        addVisitation.setVisible(false);
        newVisitorPanel.setVisible(false);
        existingVisitorPanel.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> actionType;
    private javax.swing.JPanel addVisitation;
    private javax.swing.JComboBox<String> eVisitorDay;
    private javax.swing.JComboBox<String> eVisitorDay1;
    private javax.swing.JComboBox<String> eVisitorGender;
    private javax.swing.JComboBox<String> eVisitorGender1;
    private javax.swing.JTextField eVisitorID;
    private javax.swing.JTextField eVisitorID1;
    private javax.swing.JTextField eVisitorIdNumber;
    private javax.swing.JTextField eVisitorIdNumber1;
    private javax.swing.JComboBox<String> eVisitorMonth;
    private javax.swing.JComboBox<String> eVisitorMonth1;
    private javax.swing.JTextField eVisitorName;
    private javax.swing.JTextField eVisitorName1;
    private javax.swing.JTextField eVisitorYear;
    private javax.swing.JComboBox<String> eVisitorYear1;
    private javax.swing.JRadioButton existingVisitor;
    private javax.swing.JPanel existingVisitorPanel;
    private javax.swing.JPanel existingVisitorPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> nVisitorDay;
    private javax.swing.JComboBox<String> nVisitorGender;
    private javax.swing.JTextField nVisitorIdNumber;
    private javax.swing.JComboBox<String> nVisitorMonth;
    private javax.swing.JTextField nVisitorName;
    private javax.swing.JComboBox<String> nVisitorYear;
    private javax.swing.JRadioButton newVisitor;
    private javax.swing.JPanel newVisitorPanel;
    private javax.swing.JLabel prisonerStatus;
    private javax.swing.JComboBox<String> visitDay;
    private javax.swing.JComboBox<String> visitHour;
    private javax.swing.JComboBox<String> visitMonth;
    private javax.swing.JComboBox<String> visitTime;
    private javax.swing.JComboBox<String> visitYear;
    private javax.swing.JTextField visitationId;
    private javax.swing.JLabel visitorStatus;
    // End of variables declaration//GEN-END:variables
}
